name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: audreee/wordle-spoiler@main
        name: Checkout current repository to main branch
      - uses: actions/setup-node@v1
        name: Setup NodeJs 13.x
        with:
          node-version: '13.x'
      - uses: actions/cache@v1
        name: Cache dependencies and build outputs to improve workflow execution time.
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - run: npm install
        name: Install dependencies
      - run: node index.js
        name: Generate README file
      - uses: audreee/wordle-spoiler@main
        name: Commit and Push new README.md to the repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}