name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout current repository to main branch
      - uses: actions/setup-node@v1
        name: Setup NodeJS
        with:
          node-version: '14.x'
      - uses: actions/cache@v1
        name: Cache dependencies and build outputs to improve workflow execution time.
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - run: npm install
        name: Install dependencies
      - run: node index.js
        name: Generate README file
      - name: Commit and push if changed
        run: |-
          git add .
          git diff
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push